Repository AtilioA/AlertaDoTesouro, pull requests merged in 2022-05, with the labels that each got.

#29 Use `docker compose` to run locally
  .gitignore
  README.md
  compose.yaml
  server/.env.example
  server/src/config/auth.example.ts
  server/src/config/auth.ts
  server/src/config/mail.example.ts
  server/src/config/mail.ts
  server/src/config/redis.example.ts
  server/src/config/redis.ts
Labels: back-end, enhancement, front-end

#40 Create ToS and Privacy Statement
  web/package.json
  web/src/pages/Account/index.tsx
  web/src/pages/SignIn/index.tsx
  web/src/pages/SignUp/index.tsx
  web/src/pages/SignUp/styles.ts
  web/src/pages/ToS/ToS.md
  web/src/pages/ToS/index.tsx
  web/src/pages/ToS/styles.ts
  web/src/routes/index.tsx
  web/yarn.lock
Labels: enhancement, front-end

#35 Improve documentation
  .gitignore
  server/package.json
  server/src/app.ts
  server/src/jobs/NotifyBondReturns.ts
  server/src/jobs/SendConfirmAccountMail.ts
  server/src/middlewares/ensureAuthenticated.ts
  server/src/middlewares/requestsLogger.ts
  server/src/models/Notification.ts
  server/src/models/TreasuryBond.ts
  server/src/models/User.ts
  server/src/repositories/NotificationsRepository.ts
  server/src/routes/email.routes.ts
  server/src/routes/index.ts
  server/src/routes/notifications.routes.ts
  server/src/routes/sessions.routes.ts
  server/src/routes/treasurybonds.routes.ts
  server/src/routes/users.routes.ts
  server/src/server.ts
  server/src/services/CheckNotificationsValueService.ts
  server/src/services/CreateNotificationService.ts
  server/src/services/CreateTreasuryBondService.ts
  server/src/services/CreateUserService.ts
  server/src/services/CreateUserSessionService.ts
  server/src/services/DeleteNotificationService.ts
  server/src/services/DeleteUserService.ts
  server/src/services/MailService.ts
  server/src/services/Queue.ts
  server/src/services/UpdateNotificationService.ts
  server/src/services/UpdateTreasuryBondService.ts
  server/src/services/UpdateUserService.ts
  server/src/tasks.ts
  server/src/utils/fetchTBAPI.ts
  server/src/utils/loadRequiredEnv.ts
  server/tsconfig.json
  server/yarn.lock
Labels: documentation
